project:
  type: website
  output-dir: docs

website:
  title: "OpenStack Korea Community"
  navbar:
    background: primary
    search: true
    left:
      - text: "홈"
        file: index.qmd
      - text: "실습 가이드"
        menu:
          - text: "기본 실습"
            file: guides/basic.qmd
          - text: "고급 실습"
            file: guides/advanced.qmd
      - text: "강의 자료"
        file: lectures/index.qmd
      - text: "커뮤니티"
        file: community.qmd
    right:
      - icon: github
        href: https://github.com/openstack-kr
      - icon: slack
        href: https://openstack-kr.slack.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: ko
